Table Managers {
	id int [pk]
	name varchar
	email varchar
}

Table ManagerBand {
    managerId int [ref: - Managers.id]
    bandId int [ref: > Band.id]
}

Table ManagerArtist {
    managerId int [ref: - Managers.id]
    artistId int [ref: > Artist.id]
}

Table Band {
	id int [pk]
	bandName varchar
	genre varchar
}

Table Artist {
    id int [pk]
    artistName varchar
    genre varchar
}

Table Venues {
	id int [pk]
	name varchar
	location varchar
}

Table BandVenue {
	bandId int [ref: > Band.id]
	venueId int [ref: > Venues.id]
}

Table ArtistVenue {
	userId int [ref: > Artist.id]
	venueId int [ref: > Venues.id]
}

Table MusicPlatforms {
	id int [pk]
	name varchar
}

Table ArtistMusic {
	userId int [ref: - Artist.id]
	musicLink url
	platformId int [ref: > MusicPlatforms.id]
}

Table BandMusic {
	bandId int [ref: - Band.id]
	musicLink url
	platformId int [ref: > MusicPlatforms.id]
}
