Table Managers {
	id int [pk]
	name varchar
	email varchar
}

Table Artist {
    id int [pk]
    artistName varchar
    genreId int [ref: > Genre.id]
	managerId int [ref: > Managers.id]
	isBand boolean
}

Table Genre {
	id int [pk]
	genreName varchar
}

Table Venues {
	id int [pk]
	name varchar
	latitude varchar
	longitude varchar
	location varchar
	link url
}

Table ArtistShow {
	id int [pk]
	artistId int [ref: > Artist.id]
	venueId int [ref: > Venues.id]
	link url
	showDate date
}

Table MusicPlatforms {
	id int [pk]
	name varchar
}

Table ArtistMusic {
	id int [pk]
	artistId int [ref: - Artist.id]
	musicLink url
	platformId int [ref: > MusicPlatforms.id]
}
