Table Managers {
	id int [pk]
	name varchar
	email varchar
}

Table Artists {
    id int [pk]
    name varchar
    genreId int [ref: > Genre.id]
	managerId int [ref: > Managers.id]
	isBand boolean
}

Table Genre {
	id int [pk]
	genreName varchar
}

Table Venues {
	id int [pk]
	name varchar
	latitude varchar
	longitude varchar
}

Table ArtistShows {
	id int [pk]
	artistId int [ref: > Artists.id]
	venueId int [ref: > Venues.id]
	eventTitle varchar
	link url
	date date
	startTime time
	endTime time
	intimate boolean
}

Table OpenMics {
	id int [pk]
	eventTitle varchar
	venueId int [ref: > Venues.id]
	managerId int [ref: > Managers.id]
	isRecurring boolean
	dateTime datetime
	recurrence varchar
	time time
	dayOfWeek varchar
	dayOfMonth varchar
}
